<?php
    define('IMG', 'app/data/img/');
    function findProfilePicture() {
        if(isset($_SESSION['USER'])) {
          $imgPath = IMG . '/' . explode('@', $_SESSION['USER'])[0] . '.jpg';
          if (file_exists($imgPath)) {
            return $imgPath;
          }
          return IMG . '/' . 'default.jpg';
        }
      }
?>

<?php include 'header.phtml' ?>

<link rel="stylesheet" href="assets/css/editProfile.css">
<!--..............Edit Profile...........-->


<div class="container backgrnd rounded bg-white mt-5">
<form action="" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                    <img class="rounded-circle mt-5" src="<?=findProfilePicture()?>" width="90">
                    <span class="font-weight-bold">Change Profile Picture</span>
                    <input type="file" name="pfp" id="pfp" >
                </div>
            </div>
            <div class="col-md-8">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h6 class="text-right">Edit Profile</h6>
                    </div>
                    <div class="row mt-2">
                        <div class="col-md-6"><input name="name" type="text" class="form-control" value="<?=$this->data['user']['name']?>"></div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <label for="bio">Bio:</label>
                            <?php 
                                if (isset($this->data['user']['bio'])) {
                                    echo '<textarea name="bio" id="bio" cols="50" rows="5">'. $this->data['user']['bio'] .'</textarea>';
                                }
                                else {
                                    echo '<textarea name="bio" id="bio" cols="50" rows="5" placeholder="Add a Bio."></textarea>';
                                }
                            ?>
                        </div>
                        
                    </div>  
                    <p id="response" class="h5"><?= empty($this->data['response']) && isset($_POST['submit']) ? 'Profile Updated!' : $this->data['response']  ?></p>
                 
                    <div class="mt-5 text-right"><button class="btn btn-primary profile-button" type="submit" name="submit" value="submit">Save Profile</button></div>
                </div>
            </div>
        </div>
    </div>
</form>
<?php include 'footer.phtml' ?>