
    <!--footer-->
    <footer class="bg-dark text-white pt-5 pb-4">
        <div class="container text-center text-md-left">
            <div class="row text-center text-md-left">
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h5 class="text-uppercase mb-4 font-weight-bold voyage">About us</h5>
                    <p>"Welcome aboard Learning Voyage! Your gateway to boundless learning experiences. Explore our curated pathways, discover new skills, and join a community passionate about education. Start your journey today toward a brighter, more knowledgeable tomorrow!"</p>
                </div>
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold voyage">READ ME</h5>
                <p>
                    <a href="readme.pdf" target="_blank" style="text-decoration: none;" class="link-danger h5">Link To readme.pdf</a>
                </p>
                </div>
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                <h5 class="text-uppercase mb-4 font-weight-bold voyage">Supports</h5>
                <p>
                    <a href="#" style="text-decoration: none;" class="text-white">Skill Plan</a>
                </p>
                <p>
                    <a href="#" style="text-decoration: none;" class="text-white">Flow Plan</a>
                </p>
                <p>
                    <a href="#" style="text-decoration: none;" class="text-white">Help Center</a>
                </p>
                <p>
                    <a href="#" style="text-decoration: none;" class="text-white">Cloud Guru</a>
                </p>
                </div>
                
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                <h5 class="mb-4"><span><span class="material-symbols-outlined">school</span>Learning<span class="voyage">Voyage</span></span></h5>
                <p>
                    <i class="fas fa-home mr-3"></i>Toronto, ON , Canada.
                </p>
                <p>
                    <i class="fas fa-envelope mr-3"></i>learningvoyage123@gmail.com
                </p>
                <p>
                    <i class="fas fa-phone mr-3"></i>+647 880 1567
                </p>
                <p>
                    <i class="fas fa-print mr-3"></i>+01 335 227 99
                </p>
                </div>
            </div>
            <hr class="mb-4">
        <div class="row align-items-center">
            <div class="col-md-7 col-lg-8">
                <p>
                   Copyright 2023 All rights reserved <body>
                    <a href="#" style="color: white;  text-decoration: none;"class="td-none"><span><span class="material-symbols-outlined">school</span>Learning<span class="voyage">Voyage</span></span></a>
                </p>
           </div>
           <div class="col-md-5 col-lg-4">
            <div class="text-center text-mid-right">
                <ul class="list-unstyled list-inline">
                    <li class="list-inline-item">
                        <a href="#" class="btn-floating btn-sm text-white" style="font-size: 23px;"><i class="fab fa-facebook"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="btn-floating btn-sm text-white" style="font-size: 23px;"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="btn-floating btn-sm text-white" style="font-size: 23px;"><i class="fab fa-google-plus"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="btn-floating btn-sm text-white" style="font-size: 23px;"><i class="fab fa-linkedin"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="btn-floating btn-sm text-white" style="font-size: 23px;"><i class="fab fa-youtube"></i></a>
                    </li>
                </ul>
            </div>
           </div>
        </div>
        </div>
    </footer>
  
    </div> 
  

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>  
</body>
</html>