<?php
  function createCourseDropDownTag($category) {
    // <li><a class="dropdown-item" href="#">PHP</a></li>
    echo "<li>";
    echo '<a class="dropdown-item" href="?page=paths&category=' . $category['id'] . '">' . $category['name'] . '</a>';
    echo "</li>"; 
  }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Kdam+Thmor+Pro&family=Roboto+Serif:opsz@8..144&family=Roboto:ital,wght@1,100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Home</title>
</head>
<body>
    <div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <span class="navbar-brand mb-0 h1"><span class="material-symbols-outlined">school</span>Learning<span class="voyage">Voyage</span></span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="?page=index">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Courses
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <?php
              foreach ($this->data['categories'] as $category) {
                createCourseDropDownTag($category);
              }
            ?>            
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="?page=paths">Paths</a>
        </li>
        <?php
        echo isset($_SESSION['LOGIN_STATUS']) && $_SESSION['LOGIN_STATUS'] ? '<li class="nav-item">' .
         '<a class="nav-link" href="?page=profile&user=' . $_SESSION['USER'] . '">Profile</a>' . '</li>' : '';              
        ?>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <span class="material-symbols-outlined">account_circle</span>
      <?php  echo isset($_SESSION['LOGIN_STATUS']) && $_SESSION['LOGIN_STATUS'] ? '<span class="nav-item"><a class="register voyage" href="?page=logout">Log-Out</a></span>' : 
      '<span class="nav-item"><a class="register voyage" href="?page=login">Sign-On</a></span>'
      ?>
    </div>
  </div>
</nav>
    

