<?php
  define('IMG', 'app/data/img/');
  function findProfilePicture() {
    if(isset($_SESSION['USER'])) {
      $imgPath = IMG . '/' . explode('@', $_SESSION['USER'])[0] . '.jpg';
      if (file_exists($imgPath)) {
        return $imgPath;
      }
      return IMG . '/' . 'default.jpg';
    }
  }
  function createPathRow($path) {
    echo '<tr>';
    echo '<th scope="row"><a href="?page=resources&path=' . $path['path_id'] . '">' . $path['title'] . '</a></th>';
    echo '<td>' . $path['author_name'] . '</td>';
    echo '<td>' . $path['last_updated'] . '</td>';
    echo '<td><button name="delete" value="' . $path['path_id'] . '" type="submit" class="btn btn-danger">Delete <i class="fas fa-trash-alt"></i></button></td>';
    echo '</tr>';
  }
?>

<?php include 'header.phtml' ?>


<section class="h-100 gradient-custom-2" style="background: -webkit-linear-gradient(to right, rgba(251, 194, 235, 1), rgba(166, 193, 238, 1));
  background: linear-gradient(to right, rgba(251, 194, 235, 1), rgba(166, 193, 238, 1))">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
              <img src= <?= findProfilePicture() ?>
                alt="Generic placeholder image" class="img-fluid img-thumbnail mt-4 mb-2"
                style="width: 150px;height: 180px; z-index: 1">
              <a href="?page=editProfile&user=<?=$this->data['user']['user_id']?>" class="btn btn-outline-dark" data-mdb-ripple-color="dark"
                style="z-index: 1;">
                Edit profile
              </a>
            </div>
            <div class="ms-3" style="margin-top: 130px;">
              <h2><?= $this->data['user']['name'] ?></h2>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-end text-center py-1">
              <div>
                <p class="mb-1 h5">253</p>
                <p class="small text-muted mb-0">Paths</p>
              </div>
              <div class="px-3">
                <p class="mb-1 h5">1026</p>
                <p class="small text-muted mb-0">Followers</p>
              </div>
              <div>
                <p class="mb-1 h5">478</p>
                <p class="small text-muted mb-0">Following</p>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">About</p>
              <div class="p-4"  style="background-color: #f8f9fa;color:#212121;">
                <p class="font-italic mb-1 profile-clr"></p><?= $this->data['user']['bio'] ?? 'Add a bio.' ?></p>
                
            </div>
            <div class="d-flex justify-content-between align-items-center mb-4">
              <p class="lead fw-normal mb-0">My Paths</p>
              <p class="mb-0"><a href="?page=paths&author=<?= $this->data['user']['user_id']?>" class="text-muted">Show all</a></p>
            </div>
            <div class="row g-2">
              <!--table-->
<form action="" method="POST">
<div class="table-responsive">
<table class="table table-success table-striped table-hover caption-top">
<caption>List of Paths :</caption>
  <thead>
    <tr class="table table-danger">
      <th scope="col">Title</th>
      <th scope="col">Original Author</th>
      <th scope="col">Last Update</th>
      <th scope="col">Delete path?</th>
    </tr>
  </thead>
  <tbody>
    <?php
      foreach ($this->data['userPaths'] as $path) {
        createPathRow($path);
      }
    ?>
  </tbody>
</table>
<div>
</form>
<a href="?page=addPath&author=<?=$this->data['user']['user_id']?>" class="btn btn-primary">Create a new Path</a></div>
</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!--footer-->
<?php include 'footer.phtml' ?>